%% ==========================================================
% Extract simulation outputs
% ==========================================================

yref_out  = out.yref_out;
y_out     = out.y_out;
ey_out    = out.ey_out;
delta_out = out.delta_out;
Chat_out  = out.Chat_out;
Vy_out    = out.Vy_out;
r_out     = out.r_out;
psi_out   = out.psi_out;

%% ==========================================================
% Calculate error indices
% ==========================================================

ey = ey_out.Data;
delta = delta_out.Data;
Chat = Chat_out.Data;

RMSE = sqrt(mean(ey.^2));
MaxError = max(abs(ey));
MeanError = mean(abs(ey));

FinalChat = Chat(end);
TrueC = 60000;

AbsEstError = abs(FinalChat - TrueC);
PercentEstError = 100 * AbsEstError / TrueC;

deltaMax = 0.25;
SaturationPercent = 100 * sum(abs(delta) >= 0.249) / length(delta);

fprintf('Vehicle speed = %.2f km/h\n', Vx*3.6);
fprintf('RMSE lateral error = %.4f m\n', RMSE);
fprintf('Maximum lateral error = %.4f m\n', MaxError);
fprintf('Mean absolute lateral error = %.4f m\n', MeanError);
fprintf('Final estimated C_alpha = %.2f N/rad\n', FinalChat);
fprintf('Absolute estimation error = %.2f N/rad\n', AbsEstError);
fprintf('Percentage estimation error = %.4f %%\n', PercentEstError);
fprintf('Steering saturation percentage = %.2f %%\n', SaturationPercent);

%% ==========================================================
% Plot 1: Path tracking response
% ==========================================================

figure;
plot(yref_out.Time, yref_out.Data, 'LineWidth', 1.8);
hold on;
plot(y_out.Time, y_out.Data, '--', 'LineWidth', 1.8);
grid on;
xlabel('Time (s)');
ylabel('Lateral position y (m)');
legend('Reference y_{ref}', 'Vehicle y', 'Location', 'best');
title(['Path Tracking Response at V_x = ', num2str(Vx*3.6), ' km/h']);

%% ==========================================================
% Plot 2: Lateral tracking error
% ==========================================================

figure;
plot(ey_out.Time, ey_out.Data, 'LineWidth', 1.8);
grid on;
xlabel('Time (s)');
ylabel('Lateral error e_y = y - y_{ref} (m)');
title(['Lateral Tracking Error at V_x = ', num2str(Vx*3.6), ' km/h']);

%% ==========================================================
% Plot 3: Steering input with saturation limits
% ==========================================================

figure;
plot(delta_out.Time, delta_out.Data, 'LineWidth', 1.8);
hold on;
yline(deltaMax, '--', 'Upper saturation limit');
yline(-deltaMax, '--', 'Lower saturation limit');
grid on;
xlabel('Time (s)');
ylabel('Steering angle \delta_f (rad)');
title(['Steering Input Generated by STR at V_x = ', num2str(Vx*3.6), ' km/h']);
legend('\delta_f', '+\delta_{max}', '-\delta_{max}', 'Location', 'best');

%% ==========================================================
% Plot 4: RLS estimation of tire cornering stiffness
% ==========================================================

figure;
plot(Chat_out.Time, Chat_out.Data, 'LineWidth', 1.8);
hold on;
yline(TrueC, '--', 'True C_\alpha');
grid on;
xlabel('Time (s)');
ylabel('Estimated C_\alpha (N/rad)');
title(['RLS Estimation of Tire Cornering Stiffness at V_x = ', num2str(Vx*3.6), ' km/h']);
legend('Estimated C_\alpha', 'True C_\alpha', 'Location', 'best');